### ISSUE TITLE
Should I move intro notebook to Tutorial?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/aas229_workshop#6]
What is the difference between "lecture" and "interactive"? Aren't all notebooks interactive? Should I move my intro notebooks from "lecture" to "interactive"?

**Comment by sosey** [comment]
Put the notebook you're going to lecture from into the "lecture" folder, and any other notebooks that they might use as tutorials or examples into the "tutorial" directory.

**Comment by pllim** [comment]
Okay. I guess mine can stay in "lecture" then. Thanks for the clarifications!
